sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hench100/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hench100/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-319220611842"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY